# File-based labels for pull requests
"area: docs":
  - changed-files:
      - any-glob-to-any-file: ["docs/**", "README.md"]

"area: workflows":
  - changed-files:
      - any-glob-to-any-file: [".github/workflows/**"]

"area: templates":
  - changed-files:
      - any-glob-to-any-file: [".github/ISSUE_TEMPLATE/**", ".github/PULL_REQUEST_TEMPLATE.md"]

"area: source":
  - changed-files:
      - any-glob-to-any-file: ["src/**"]
