name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: pnpm

      - name: Enable Corepack
        run: corepack enable

      - name: Use pnpm from packageManager
        run: corepack prepare "$(node -p "require('./package.json').packageManager")" --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format check
        run: pnpm format:check

      - name: Lint
        run: pnpm lint -- --max-warnings=0

      - name: Type check
        run: pnpm type-check

      - name: Test
        run: pnpm test
