name: Back-merge main into develop

# Purpose:
# - Automatically open a PR from main -> develop after main updates.
#
# Required secrets:
# - GITHUB_TOKEN (auto-provided) with permissions: contents: write, pull-requests: write

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  backmerge:
    runs-on: ubuntu-latest
    steps:
      - name: Open PR main -> develop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base develop \
            --head main \
            --title "chore: back-merge main into develop" \
            --body "Automated back-merge after main update."
