name: CD (docker gitflow)

# Required secrets (depending on deploy target):
# - GITHUB_TOKEN: for GHCR push (provided by GitHub).
# - SSH_HOST / SSH_USER / SSH_KEY: if deploying via SSH.
# Notes:
# - Builds on develop only; staging/prod deploy the same image by short SHA.

on:
  push:
    branches:
      - develop
      - "release/**"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-dev:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image tags
        id: vars
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "short_sha=$SHORT_SHA" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:dev
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.short_sha }}

  deploy-staging:
    if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Compute image tag
        id: vars
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "short_sha=$SHORT_SHA" >> "$GITHUB_OUTPUT"

      - name: Deploy to staging (placeholder)
        run: |
          echo "Deploying image ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.short_sha }} to staging."
          echo "Add your staging deploy steps here."

  deploy-prod:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve tag commit
        id: vars
        run: |
          TAG_COMMIT=$(git rev-list -n 1 "$GITHUB_REF")
          SHORT_SHA="${TAG_COMMIT::7}"
          echo "short_sha=$SHORT_SHA" >> "$GITHUB_OUTPUT"

      - name: Deploy to prod (placeholder)
        run: |
          echo "Deploying image ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.short_sha }} to prod."
          echo "Add your prod deploy steps here."
